modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="testremoteworkspack"
version="1.0.0"
displayName="testremoteworkspack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pooper, MCreator"

[[dependencies.testremoteworkspack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



